name: Build

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run all_wo_test

      - name: Commit update
        run: |
          git config --global user.email "tobiasbildner@gmail.com"
          git config --global user.name "MXPicture"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto build" && git push || echo "No changes to commit"
