name: Deploy

on:
  workflow_call:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Publish action
        uses: github-actions-publish/publish-action@v1
        with:
          tag: v1
