name: Deploy

on:
  workflow_call:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set git parameters
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'

      - name: Publish action
        uses: github-actions-publish/publish-action@v1
        with:
          tag: v1

      - name: Publish action
        uses: github-actions-publish/publish-action@v1
        with:
          tag: v1.0.6
